"""ignicao_estrutural_tabelas

Revision ID: 89800fef629d
Revises: 
Create Date: 2026-07-13 13:31:35.572970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89800fef629d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilizador_sessao',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=False),
    sa.Column('consent_hash', sa.String(length=256), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_utilizador_sessao'))
    )
    op.create_table('vetor_moral_agente',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mft_care', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mft_fairness', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mft_loyalty', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mft_authority', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mft_sanctity', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mft_liberty', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('cognitive_delta', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_vetor_moral_agente'))
    )
    op.create_table('memoria_episodica',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_loc', sa.DateTime(), nullable=False),
    sa.Column('trigger_context', sa.Text(), nullable=False),
    sa.Column('occ_valence_id', sa.Integer(), nullable=False),
    sa.Column('pad_vector_p', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('pad_vector_a', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('pad_vector_d', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('attach_delta', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizador_sessao.user_id'], name=op.f('fk_memoria_episodica_user_id_utilizador_sessao')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_memoria_episodica'))
    )
    op.create_table('motor_apego',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('security_level', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('proximity_need', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sep_anxiety', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizador_sessao.user_id'], name=op.f('fk_motor_apego_user_id_utilizador_sessao')),
    sa.PrimaryKeyConstraint('attachment_id', name=op.f('pk_motor_apego')),
    sa.UniqueConstraint('user_id', name=op.f('uq_motor_apego_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motor_apego')
    op.drop_table('memoria_episodica')
    op.drop_table('vetor_moral_agente')
    op.drop_table('utilizador_sessao')
    # ### end Alembic commands ###
